#!/usr/bin/env python
"""
Generate golden per-bin likelihood values from NNMFit's own likelihood graphs.

The values are produced by NNMFit's aesara graphs (SAYLLH.compute_log_L and
PoissonLLH.compute_log_L), not by a re-implementation, so the emitted header is
a reference dump of the code PhyLiNO must match rather than a second opinion.

Run with NNMFit's interpreter:

    /Users/soldin/Projects/IceCube/NNMFit/.venv/bin/python \
        tools/nnmfit_oracle/gen_llh_golden.py \
        -o programs/ictests/LLHGolden.inc

The emitted file is committed; regenerate it only when NNMFit's likelihood
implementation changes.
"""

import argparse
import numpy as np

from NNMFit.likelihoods.impl.say_llh import SAYLLH
from NNMFit.likelihoods.impl.poisson_llh import PoissonLLH
from NNMFit.tensor.manager import get_backend

T = get_backend()["current"]


def _compile(build):
    """Compile a graph f(k, mu, ssq) built by `build` into a numpy callable."""
    shape = (1,)
    variables = {
        name: T.shared_var(np.zeros(shape), name, const=False)
        for name in ("k", "mu", "ssq")
    }
    func = T.function(build(variables))

    def call(k, mu, ssq):
        for name, value in (("k", k), ("mu", mu), ("ssq", ssq)):
            T.set_value(variables[name], np.array([value], dtype=float))
        return float(func()[0])

    return call


say = _compile(lambda v: SAYLLH.compute_log_L(k=v["k"], mu=v["mu"], ssq=v["ssq"]))

poisson = _compile(lambda v: PoissonLLH.compute_log_L(k=v["k"], mu=v["mu"]))

# What LikelihoodBuilder actually minimises for llh == "PoissonLLH":
# make_llh(substract_saturated=True) -> logP(k|mu) - logP(k|k).
poisson_saturated = _compile(
    lambda v: PoissonLLH.compute_log_L(k=v["k"], mu=v["mu"])
    - PoissonLLH.compute_log_L(k=v["k"], mu=v["k"])
)

# (k, mu, ssq). ssq is ignored by the Poisson cases.
CASES = [
    # ordinary bins
    (12.0, 10.0, 3.0),
    (0.0, 10.0, 3.0),
    (1000.0, 1010.0, 250.0),
    (3.0, 2.5, 0.4),
    # non-integer k (Asimov data is the model prediction, not a count)
    (10.25, 10.0, 2.0),
    (0.5, 0.4, 0.01),
    # ssq == 0 -> Poisson limit
    (7.0, 6.0, 0.0),
    (0.0, 6.0, 0.0),
    # ssq > mu**2 -> clipped to mu**2
    (7.0, 2.0, 100.0),
    # ssq < 0 -> clipped to 0, i.e. the Poisson limit
    (7.0, 6.0, -1.0),
    # mu == 0 -> -690 * k / 0
    (5.0, 0.0, 1.0),
    (0.0, 0.0, 1.0),
    (5.0, 0.0, 0.0),
    # mu < 0 (cannot arise after the prediction clip, but the switch is defined)
    (5.0, -1.0, 1.0),
    # tiny mu, large k: the numerically nastiest ordinary case
    (50.0, 1e-6, 1e-9),
    # large-statistics bin
    (250000.0, 249000.0, 12000.0),
]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-o", "--output", required=True, help="header to write")
    args = parser.parse_args()

    rows = []
    for k, mu, ssq in CASES:
        rows.append(
            "    {{{:.17g}, {:.17g}, {:.17g}, {:.17g}, {:.17g}, {:.17g}}},".format(
                k, mu, ssq, say(k, mu, ssq), poisson(k, mu, ssq),
                poisson_saturated(k, mu, ssq),
            )
        )

    with open(args.output, "w") as out:
        out.write(
            "// Generated by tools/nnmfit_oracle/gen_llh_golden.py -- do not edit.\n"
            "//\n"
            "// Per-bin log-likelihood values dumped from NNMFit's own aesara graphs\n"
            "// (SAYLLH.compute_log_L, PoissonLLH.compute_log_L, and the saturated-\n"
            "// subtracted Poisson that LikelihoodBuilder builds by default).\n"
            "// Columns: k, mu, ssq, say, poisson, poisson_saturated_subtracted.\n"
            "\n"
            "struct LLHGoldenCase {\n"
            "  double k;\n"
            "  double mu;\n"
            "  double ssq;\n"
            "  double say;\n"
            "  double poisson;\n"
            "  double poisson_saturated;\n"
            "};\n"
            "\n"
            "static constexpr LLHGoldenCase kLLHGolden[] = {\n"
        )
        out.write("\n".join(rows))
        out.write("\n};\n")

    print(f"wrote {len(rows)} cases to {args.output}")


if __name__ == "__main__":
    main()
